### ISSUE TITLE
Hyper Protect DBaaS free plan is not offered with IBM Lite account.

### ISSUE THREAD

**Issue by aaronralls** [ibm-cloud-docs/hyper-protect-dbaas-for-mongodb#1]
This statement needs to be updated to say the Pay-As-You-Go account vs the Lite account.

"You can create a 30-day free plan service instance with a Lite IBM Cloud account."

**Comment by PanLiyuan** [comment]
@aaronralls Thank you for the feedback! I will confirm with the offering team and revise the documentation.

**Comment by PanLiyuan** [comment]
@aaronralls I have changed the statement in the [documentation](https://cloud.ibm.com/docs/hyper-protect-dbaas-for-mongodb?topic=hyper-protect-dbaas-for-mongodb-gettingstarted#prerequisite). Thank you again for pointing that out! Could you close this issue if there's no other comments?
