### ISSUE TITLE
Not able to find additional parameters especially on KMS integration

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/hyper-protect-dbaas-for-mongodb#2]
The documentation states to check on the table for the CLI documentation. 
There is no table describing the additional parameters

Esepcially it would be important to update or provide information about the KMS integration for the HPDBaaS offering

**Comment by stschmitt** [comment]
I just saw that there is a top level navigarion tab showing CLI. This is a bit confusing to have multiple clicks. 
Honestly my eye do not catch the change at the top. 
In any case I think it would be good to show the KMS integration in the sample

**Comment by PanLiyuan** [comment]
@stschmitt Just to confirm, are you talking about the Terraform sample?
The CLI link is supposed to take you to this part **Creating a service instance from the CLI** directly, but there's some problems with the tab switching, which the cloud docs team is working on. I know the experience isn't great now. I've just passed on the feedback to them again.

**Comment by stschmitt** [comment]
Yes I talk about the Terraform example. The Example links to the CLI table for further reference. Which is ok, I personally would this we should have more sample attributes within the sample script as well

**Comment by PanLiyuan** [comment]
@stschmitt thanks for the suggestion. I'll bring it to the dev team.

**Comment by PanLiyuan** [comment]
Hi Stefan @stschmitt , KMS parameters are added to the samples. Could you close this issue? Thank you!

- PostgreSQL
https://cloud.ibm.com/docs/hyper-protect-dbaas-for-postgresql?topic=hyper-protect-dbaas-for-postgresql-terraform-setup#work-with-dbaas-resources
- MongoDB
https://cloud.ibm.com/docs/hyper-protect-dbaas-for-mongodb?topic=hyper-protect-dbaas-for-mongodb-terraform-setup#work-with-dbaas-resources

**Comment by stschmitt** [comment]
Thanks close it
